openapi: 3.0.1
info:
  contact:
    email: support@rixl.com
    name: RIXL Support
    url: https://rixl.com/support
  description: |-
    **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**

    RIXL handles video processing, ingestion and global delivery so you don't have to.
    With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
  license:
    name: All Rights Reserved
    url: https://rixl.com/terms-of-service
  title: RIXL API
  version: "2.0"
servers:
- url: https://api.rixl.com/
tags:
- description: "**Build dynamic social experiences.**<br><br>Feeds are ordered collections\
    \ of Posts, designed for creating vertical video carousels, stories, or social\
    \ timelines. Each Post contains your media (video or image) and its associated\
    \ metadata."
  name: feeds
paths:
  /feeds/{feedId}:
    get:
      description: "Retrieve posts in a feed, with pagination."
      operationId: get_feeds_feedId
      parameters:
      - description: Feed ID
        in: path
        name: feedId
        required: true
        schema:
          type: string
      - description: Maximum number of items to return in a single request. <br> **Default:**
          `25`
        in: query
        name: limit
        schema:
          default: 25
          maximum: 100
          minimum: 1
          type: integer
      - description: "Starting point of the result set. <br>To get page 2 with a limit\
          \ of 25, set `offset` to `25`. <br> **Default:** `0`"
        in: query
        name: offset
        schema:
          default: 0
          minimum: 0
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/pagination.PaginatedResponse-Post"
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/github_com_qeeqez_api_internal_errors.ErrorResponse"
          description: Invalid feed ID or query parameters
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/github_com_qeeqez_api_internal_errors.ErrorResponse"
          description: Internal server error
      summary: List posts in a feed
      tags:
      - feeds
  /feeds/{feedId}/creators/{creatorId}:
    get:
      description: "Retrieve posts in a feed by a specific creator, with pagination."
      operationId: get_feeds_feedId_creators_creatorId
      parameters:
      - description: Feed ID
        in: path
        name: feedId
        required: true
        schema:
          type: string
      - description: Creator ID
        in: path
        name: creatorId
        required: true
        schema:
          type: string
      - description: Maximum number of items to return in a single request. <br> **Default:**
          `25`
        in: query
        name: limit
        schema:
          default: 25
          maximum: 100
          minimum: 1
          type: integer
      - description: "Starting point of the result set. <br>To get page 2 with a limit\
          \ of 25, set `offset` to `25`. <br> **Default:** `0`"
        in: query
        name: offset
        schema:
          default: 0
          minimum: 0
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/pagination.PaginatedResponse-Post"
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/github_com_qeeqez_api_internal_errors.ErrorResponse"
          description: "Invalid feed ID, creator ID, or query parameters"
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/github_com_qeeqez_api_internal_errors.ErrorResponse"
          description: Internal server error
      summary: List posts by creator
      tags:
      - feeds
  /feeds/{feedId}/{postId}:
    get:
      description: Retrieve a post from feed by its ID
      operationId: get_feeds_feedId_postId
      parameters:
      - description: Feed ID
        in: path
        name: feedId
        required: true
        schema:
          type: string
      - description: Post ID
        in: path
        name: postId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/github_com_qeeqez_api_internal_errors.ErrorResponse"
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/github_com_qeeqez_api_internal_errors.ErrorResponse"
          description: Not Found
      summary: Get a post
      tags:
      - feeds
components:
  schemas:
    Chapter:
      example:
        end_time_sec: 145.0
        duration_label: 02:25
        start_time_sec: 0.0
        title: Introduction
      properties:
        duration_label:
          example: 02:25
          type: string
        end_time_sec:
          example: 145.0
          type: number
        start_time_sec:
          example: 0.0
          type: number
        title:
          example: Introduction
          type: string
      type: object
    File:
      example:
        size: 1048576
        updated_at: 2025-01-01T00:00:00Z
        project_id: Bq4y3QB38S
        format: avif
        name: original.jpeg
        created_at: 2025-01-01T00:00:00Z
        id: FpvLwyDMqu
        url: https://images.rixl.com/Bq4y3QB38S/FpvLwyDMqu
        status: ready
      properties:
        created_at:
          example: 2025-01-01T00:00:00Z
          type: string
        format:
          example: avif
          type: string
        id:
          example: FpvLwyDMqu
          type: string
        name:
          example: original.jpeg
          type: string
        project_id:
          example: Bq4y3QB38S
          type: string
        size:
          example: 1048576
          type: integer
        status:
          allOf:
          - $ref: "#/components/schemas/FileStatus"
          example: ready
          type: object
        updated_at:
          example: 2025-01-01T00:00:00Z
          type: string
        url:
          example: https://images.rixl.com/Bq4y3QB38S/FpvLwyDMqu
          type: string
      type: object
    FileStatus:
      enum:
      - uploading
      - uploaded
      - processing
      - preparing
      - ready
      - error
      type: string
      x-enum-comments:
        FileStatusError: "error happened, file is corrupt"
        FileStatusProcessing: asset is currently processing Other
        FileStatusReady: file is ready to consume
        FileStatusUploaded: upload finished
        FileStatusUploading: upload is currently happening
      x-enum-varnames:
      - FileStatusUploading
      - FileStatusUploaded
      - FileStatusProcessing
      - FileStatusPreparing
      - FileStatusReady
      - FileStatusError
    Image:
      example:
        file:
          size: 1048576
          updated_at: 2025-01-01T00:00:00Z
          project_id: Bq4y3QB38S
          format: avif
          name: original.jpeg
          created_at: 2025-01-01T00:00:00Z
          id: FpvLwyDMqu
          url: https://images.rixl.com/Bq4y3QB38S/FpvLwyDMqu
          status: ready
        attached_to_video: false
        width: 1920
        id: PS5IMKoFLm
        height: 1080
        thumbhash: 1QcSHQRnh493V4dIh4eXh1h4kJUI
      properties:
        attached_to_video:
          example: false
          type: boolean
        file:
          $ref: "#/components/schemas/File"
        height:
          example: 1080
          type: integer
        id:
          example: PS5IMKoFLm
          type: string
        thumbhash:
          example: 1QcSHQRnh493V4dIh4eXh1h4kJUI
          type: string
        width:
          example: 1920
          type: integer
      type: object
    Post:
      example:
        image:
          file:
            size: 1048576
            updated_at: 2025-01-01T00:00:00Z
            project_id: Bq4y3QB38S
            format: avif
            name: original.jpeg
            created_at: 2025-01-01T00:00:00Z
            id: FpvLwyDMqu
            url: https://images.rixl.com/Bq4y3QB38S/FpvLwyDMqu
            status: ready
          attached_to_video: false
          width: 1920
          id: PS5IMKoFLm
          height: 1080
          thumbhash: 1QcSHQRnh493V4dIh4eXh1h4kJUI
        plan_type: free
        updated_at: 2025-01-01T00:00:00Z
        creator_id: CR8y3QB38S
        created_at: 2025-01-01T00:00:00Z
        description: My awesome post
        id: PS5IMKoFLm
        video:
          duration: 6.027456183070403
          codec: codec
          plan_type: free
          file:
            size: 1048576
            updated_at: 2025-01-01T00:00:00Z
            project_id: Bq4y3QB38S
            format: avif
            name: original.jpeg
            created_at: 2025-01-01T00:00:00Z
            id: FpvLwyDMqu
            url: https://images.rixl.com/Bq4y3QB38S/FpvLwyDMqu
            status: ready
          chapters:
          - end_time_sec: 145.0
            duration_label: 02:25
            start_time_sec: 0.0
            title: Introduction
          - end_time_sec: 145.0
            duration_label: 02:25
            start_time_sec: 0.0
            title: Introduction
          framerate: framerate
          hdr: true
          width: 5
          bitrate: 0
          id: id
          poster:
            file:
              size: 1048576
              updated_at: 2025-01-01T00:00:00Z
              project_id: Bq4y3QB38S
              format: avif
              name: original.jpeg
              created_at: 2025-01-01T00:00:00Z
              id: FpvLwyDMqu
              url: https://images.rixl.com/Bq4y3QB38S/FpvLwyDMqu
              status: ready
            attached_to_video: false
            width: 1920
            id: PS5IMKoFLm
            height: 1080
            thumbhash: 1QcSHQRnh493V4dIh4eXh1h4kJUI
          height: 1
        type: video
        feed_id: FD4y3QB38S
      properties:
        created_at:
          example: 2025-01-01T00:00:00Z
          type: string
        creator_id:
          example: CR8y3QB38S
          type: string
        description:
          example: My awesome post
          type: string
        feed_id:
          example: FD4y3QB38S
          type: string
        id:
          example: PS5IMKoFLm
          type: string
        image:
          $ref: "#/components/schemas/Image"
        plan_type:
          allOf:
          - $ref: "#/components/schemas/github_com_qeeqez_api_db_sqlc.PlanType"
          example: free
          type: object
        type:
          allOf:
          - $ref: "#/components/schemas/PostType"
          example: video
          type: object
        updated_at:
          example: 2025-01-01T00:00:00Z
          type: string
        video:
          $ref: "#/components/schemas/github_com_qeeqez_api_internal_videos.VideoResponse"
      type: object
    PostType:
      enum:
      - image
      - video
      type: string
      x-enum-varnames:
      - PostTypeImage
      - PostTypeVideo
    github_com_qeeqez_api_db_sqlc.PlanType:
      enum:
      - free
      - pro
      - custom
      - pay_as_you_go
      type: string
      x-enum-varnames:
      - PlanTypeFree
      - PlanTypePro
      - PlanTypeCustom
      - PlanTypePayAsYouGo
    github_com_qeeqez_api_internal_errors.ErrorResponse:
      description: Standard error response returned by the API
      example:
        code: 400
        details: The provided ID is not valid
        error: Invalid request
      properties:
        code:
          description: HTTP status code
          example: 400
          type: integer
        details:
          description: Optional details about the error
          example: The provided ID is not valid
          type: string
        error:
          description: Error message describing what went wrong
          example: Invalid request
          type: string
      type: object
    github_com_qeeqez_api_internal_videos.VideoResponse:
      example:
        duration: 6.027456183070403
        codec: codec
        plan_type: free
        file:
          size: 1048576
          updated_at: 2025-01-01T00:00:00Z
          project_id: Bq4y3QB38S
          format: avif
          name: original.jpeg
          created_at: 2025-01-01T00:00:00Z
          id: FpvLwyDMqu
          url: https://images.rixl.com/Bq4y3QB38S/FpvLwyDMqu
          status: ready
        chapters:
        - end_time_sec: 145.0
          duration_label: 02:25
          start_time_sec: 0.0
          title: Introduction
        - end_time_sec: 145.0
          duration_label: 02:25
          start_time_sec: 0.0
          title: Introduction
        framerate: framerate
        hdr: true
        width: 5
        bitrate: 0
        id: id
        poster:
          file:
            size: 1048576
            updated_at: 2025-01-01T00:00:00Z
            project_id: Bq4y3QB38S
            format: avif
            name: original.jpeg
            created_at: 2025-01-01T00:00:00Z
            id: FpvLwyDMqu
            url: https://images.rixl.com/Bq4y3QB38S/FpvLwyDMqu
            status: ready
          attached_to_video: false
          width: 1920
          id: PS5IMKoFLm
          height: 1080
          thumbhash: 1QcSHQRnh493V4dIh4eXh1h4kJUI
        height: 1
      properties:
        bitrate:
          type: integer
        chapters:
          items:
            $ref: "#/components/schemas/Chapter"
          type: array
        codec:
          type: string
        duration:
          type: number
        file:
          $ref: "#/components/schemas/File"
        framerate:
          type: string
        hdr:
          type: boolean
        height:
          type: integer
        id:
          type: string
        plan_type:
          allOf:
          - $ref: "#/components/schemas/github_com_qeeqez_api_db_sqlc.PlanType"
          example: free
          type: object
        poster:
          $ref: "#/components/schemas/Image"
        width:
          type: integer
      type: object
    pagination.PaginatedResponse-Post:
      example:
        pagination: "{}"
        data:
        - image:
            file:
              size: 1048576
              updated_at: 2025-01-01T00:00:00Z
              project_id: Bq4y3QB38S
              format: avif
              name: original.jpeg
              created_at: 2025-01-01T00:00:00Z
              id: FpvLwyDMqu
              url: https://images.rixl.com/Bq4y3QB38S/FpvLwyDMqu
              status: ready
            attached_to_video: false
            width: 1920
            id: PS5IMKoFLm
            height: 1080
            thumbhash: 1QcSHQRnh493V4dIh4eXh1h4kJUI
          plan_type: free
          updated_at: 2025-01-01T00:00:00Z
          creator_id: CR8y3QB38S
          created_at: 2025-01-01T00:00:00Z
          description: My awesome post
          id: PS5IMKoFLm
          video:
            duration: 6.027456183070403
            codec: codec
            plan_type: free
            file:
              size: 1048576
              updated_at: 2025-01-01T00:00:00Z
              project_id: Bq4y3QB38S
              format: avif
              name: original.jpeg
              created_at: 2025-01-01T00:00:00Z
              id: FpvLwyDMqu
              url: https://images.rixl.com/Bq4y3QB38S/FpvLwyDMqu
              status: ready
            chapters:
            - end_time_sec: 145.0
              duration_label: 02:25
              start_time_sec: 0.0
              title: Introduction
            - end_time_sec: 145.0
              duration_label: 02:25
              start_time_sec: 0.0
              title: Introduction
            framerate: framerate
            hdr: true
            width: 5
            bitrate: 0
            id: id
            poster:
              file:
                size: 1048576
                updated_at: 2025-01-01T00:00:00Z
                project_id: Bq4y3QB38S
                format: avif
                name: original.jpeg
                created_at: 2025-01-01T00:00:00Z
                id: FpvLwyDMqu
                url: https://images.rixl.com/Bq4y3QB38S/FpvLwyDMqu
                status: ready
              attached_to_video: false
              width: 1920
              id: PS5IMKoFLm
              height: 1080
              thumbhash: 1QcSHQRnh493V4dIh4eXh1h4kJUI
            height: 1
          type: video
          feed_id: FD4y3QB38S
        - image:
            file:
              size: 1048576
              updated_at: 2025-01-01T00:00:00Z
              project_id: Bq4y3QB38S
              format: avif
              name: original.jpeg
              created_at: 2025-01-01T00:00:00Z
              id: FpvLwyDMqu
              url: https://images.rixl.com/Bq4y3QB38S/FpvLwyDMqu
              status: ready
            attached_to_video: false
            width: 1920
            id: PS5IMKoFLm
            height: 1080
            thumbhash: 1QcSHQRnh493V4dIh4eXh1h4kJUI
          plan_type: free
          updated_at: 2025-01-01T00:00:00Z
          creator_id: CR8y3QB38S
          created_at: 2025-01-01T00:00:00Z
          description: My awesome post
          id: PS5IMKoFLm
          video:
            duration: 6.027456183070403
            codec: codec
            plan_type: free
            file:
              size: 1048576
              updated_at: 2025-01-01T00:00:00Z
              project_id: Bq4y3QB38S
              format: avif
              name: original.jpeg
              created_at: 2025-01-01T00:00:00Z
              id: FpvLwyDMqu
              url: https://images.rixl.com/Bq4y3QB38S/FpvLwyDMqu
              status: ready
            chapters:
            - end_time_sec: 145.0
              duration_label: 02:25
              start_time_sec: 0.0
              title: Introduction
            - end_time_sec: 145.0
              duration_label: 02:25
              start_time_sec: 0.0
              title: Introduction
            framerate: framerate
            hdr: true
            width: 5
            bitrate: 0
            id: id
            poster:
              file:
                size: 1048576
                updated_at: 2025-01-01T00:00:00Z
                project_id: Bq4y3QB38S
                format: avif
                name: original.jpeg
                created_at: 2025-01-01T00:00:00Z
                id: FpvLwyDMqu
                url: https://images.rixl.com/Bq4y3QB38S/FpvLwyDMqu
                status: ready
              attached_to_video: false
              width: 1920
              id: PS5IMKoFLm
              height: 1080
              thumbhash: 1QcSHQRnh493V4dIh4eXh1h4kJUI
            height: 1
          type: video
          feed_id: FD4y3QB38S
      properties:
        data:
          description: Data contains the slice of items for the current request.
          items:
            $ref: "#/components/schemas/Post"
          type: array
        pagination:
          allOf:
          - $ref: "#/components/schemas/pagination.Pagination"
          description: Pagination data for the request.
          type: object
      type: object
    pagination.Pagination:
      properties:
        limit:
          description: Maximum number of items to return in a single request.
          example: 100
          maximum: 100
          minimum: 1
          type: integer
        offset:
          description: Starting point of the result set.
          example: 50
          minimum: 0
          type: integer
        total:
          description: The total number of available items in the full list.
          example: 1000
          minimum: 0
          type: integer
      type: object
  securitySchemes:
    ApiKeyAuth:
      description: Internal API key for service-to-service communication.
      in: header
      name: X-API-Key
      type: apiKey
x-original-swagger-version: "2.0"
